# Generated by Django 4.1.13 on 2026-05-17 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='format_type',
            field=models.CharField(default='Book', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_top_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='reading_list_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='trending_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='wishlist_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doodleuser',
            name='auto_sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doodleuser',
            name='favorite_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doodleuser',
            name='last_active_section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doodleuser',
            name='most_visited_books',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='doodleuser',
            name='most_visited_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='doodleuser',
            name='preferred_theme',
            field=models.CharField(default='dark', max_length=50),
        ),
        migrations.AddField(
            model_name='doodleuser',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='doodleuser',
            name='reading_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doodleuser',
            name='reading_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doodleuser',
            name='recently_viewed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doodleuser',
            name='wishlist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
