# Generated by Django 4.1.13 on 2026-05-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bookrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format_type',
            field=models.CharField(default='book', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='english', max_length=100),
        ),
    ]
