# Generated by Django 4.1.13 on 2026-05-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_book_format_type_alter_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
