# Generated by Django 4.1.13 on 2026-05-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bookrating_review'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookrating',
            table=None,
        ),
    ]
